In [1]:
from Annotation_helper import *

In [2]:
transactions = load_transactions("../structured_data\VOC Cochin Slave Transactions 1706-1801 - IISH - Database - 2018 - v1.csv")
permissions = load_permissions("../structured_data\VOC Cochin Slave Transport Permissions 1770-1795 - IISH - Database - 2018 - v1.csv")

In [3]:
per_to_trans = {
                "BezitterVoornaam" : ("KoperVoornaam", 2),
                "BezitterTussen": ("KoperTussen", 1),
                "BezitterAchternaam" : ("KoperAchternaam", 2),
                "SlaafNaamNieuw" : ("SlaafNaamNieuw", 2),
                "BezitterBeroep" : ("KoperBeroep", 1),
                "BezitterStatus" : ("KoperStatus", 1),
                "SlaafGender" : ("SlaafGender", 1),
                "Datum" : ("Datum", 1),
#                 "BezitterWerkplek" : "KoperWerkplek",
                "SlaafKaste" : ("SlaafKaste", 1)
}

In [4]:
generate_query(permissions.iloc[112], per_to_trans)

{'Datum': ('1770-11-30', 1),
 'KoperVoornaam': ('Christiaan', 2),
 'KoperTussen': (nan, 1),
 'KoperAchternaam': ('Borgdorp', 2),
 'KoperBeroep': ('Constabel', 1),
 'KoperStatus': ('VOC', 1),
 'SlaafNaamNieuw': ('Sarrij', 2),
 'SlaafKaste': (nan, 1),
 'SlaafGender': ('v', 1)}

In [18]:
q = generate_query(permissions.iloc[100], per_to_trans)
display(HTML(pd.DataFrame(get_n_dict_value(q), index=[0]).to_html()))
m = fuzzy_match(transactions, q)
m[get_n_dict_value(per_to_trans).values()].head(n=25)
# m.head(n=25)

,KoperVoornaam,KoperTussen,KoperAchternaam,SlaafNaamNieuw,KoperBeroep,KoperStatus,SlaafGender,Datum,SlaafKaste
4255,Hendrik,NaN,Dirksz:,Zeptember,Boekhouder en dispencier,VOC,m,1770-10-12,Bettua
4137,NaN,NaN,NaN,September,NaN,NaN,m,1770-08-07,Canara
5560,Ratenjij,NaN,NaN,September,NaN,NaN,m,1776-03-02,Poelia
4254,Hendrik,NaN,Dirtsz:,October,Boekhouder en diespencier,VOC,m,1770-10-12,Parrea
6964,NaN,NaN,NaN,September,NaN,NaN,m,1789-09-[...],Oladen Heiden
1663,Lambert,NaN,Kellensz:,September,Boekhouder,VOC,m,1764-12-05,Bettua
4666,Micdien,NaN,NaN,September,Oostersche korporaal,NaN,m,1790-12-18,Bettua
4259,Loure[ns],NaN,NaN,NaN,Schipper en Equipagie meester,VOC,m,1770-10-12,Poelia
4436,Malola,NaN,NaN,September,NaN,Vrije vrouw,m,1771-08-17,Namboebettoea
705,Philip,NaN,Philipsz:,September,Zoldaat,VOC,m,1759-10-16,Moor
1530,Mina,NaN,NaN,September,NaN,Vrijvrouw; inwoonder binnen deser steede,m,1764-09-15,Poelia
1216,Arimens,NaN,NaN,September,Staadsherbergier,NaN,m,1763-09-02,Chego
4252,He[..],NaN,Dirksz:,Augustus,Boekhouder en dispencier,VOC,m,1770-10-12,Chego
4795,Joan,NaN,Mendosz:,September,NaN,NaN,m,1791-01-19,Kanaka heiden
4197,Nicolaas,NaN,Durion,September,Bombardier,VOC,m,1770-09-11,Poelia
2254,Philip,NaN,Philipsz:,September,Soldaat,VOC,m,1767-09-02,Poelia
3874,Coenraad George,NaN,Seissert,September,Boekhouder en Soldij overdrager,VOC,m,1760-11-03,poelia
7013,Andries,NaN,NaN,NaN,NaN,NaN,m,1789-11-[...],[...]heiden
1566,Bastiaan,NaN,Jansz:,September,Bedienaar des goddelijken woords,NaN,m,1764-10-06,Chego
7162,Kandoemma,NaN,NaN,September,NaN,Wedewe: woonagtig binnen deeze stad,m,1793-11-26,Parea Heiden
3185,Aboe Poeker,NaN,NaN,September,NaN,Woonagtig te Kalwettij,m,1794-09-23,Sjego Heiden
4173,Jan Baptist,van den,Broek,September,Corporaal,VOC,m,1770-08-30,Poelia
4353,Hendrik,NaN,Dirksz:,Janijwarij,Boekhouder; dispencier,VOC,m,1770-06-28,Chego
5585,Johan Godfried,NaN,Reijckel,September,Sergeant,VOC,m,1776-03-16,Bettua
4229,Philliph,NaN,Philiphsz:,September,NaN,Vrijman,m,1770-09-29,Oeladda

In [ ]:
Annotate_data(permissions, transactions, per_to_trans, "Matches/Bas.csv")