In [12]:
from Annotation_helper import *

In [13]:
transactions = load_transactions("../../Data/structured_data\Transactions.csv")
permissions = load_permissions("../../Data/structured_data\permissions.csv")

In [14]:
permissions[permissions["ID"] == "897-3-18"]

,Unnamed: 0,ID,Permissie,Inventarisnummer,Scan,Plaats,Datum,BezitterVoornaam,BezitterTussen,BezitterAchternaam,...,BezitterEtniciteit,BezitterStatus,SlaafNaamNieuw,SlaafNaamOrigineel,SlaafKaste,SlaafGender,Opmerking,Betaling,Door[Kantlijn],Entry-ID
71,71,897-3-18,18,897,3,Cochin,1770-10-12,Philip,NaN,Philipsz:,...,NaN,Vrijman,Zeptember,NaN,NaN,m,NaN,Enz:,Hem selfs,71

In [15]:
per_to_trans = {
                "BezitterVoornaam" : ("KoperVoornaam", 2),
                "BezitterTussen": ("KoperTussen", 1),
                "BezitterAchternaam" : ("KoperAchternaam", 2),
                "BezitterGender" : ("KoperGender", 2),
                "SlaafNaamNieuw" : ("SlaafNaamNieuw", 2),
                "BezitterBeroep" : ("KoperBeroep", 1),
                "BezitterStatus" : ("KoperStatus", 1),
                "SlaafGender" : ("SlaafGender", 1),
                "Datum" : ("Datum", 1),
                "BezitterWerkplek" : ("KoperWerkplek", 1),
                "SlaafKaste" : ("SlaafKaste", 1)
}

In [17]:
a = Annotator(permissions, transactions, per_to_trans, "Matches/Bas3.csv")
a.annotate()

Query:

Possible matches:

KeyboardInterrupt: Interrupted by user